### ISSUE TITLE
Does this library suports capturePayment?

### ISSUE THREAD

**Issue by antonioperic** [thephpleague/omnipay-netaxept#3]
if not, is there any guide how to add it/

**Comment by kayladnls** [comment]
Currently this package supports purchase and complete purchase. A capturePayment action could be added. You can use the existing classes as a template: https://github.com/thephpleague/omnipay-netaxept/blob/master/src/Message/PurchaseRequest.php

**Comment by antonioperic** [comment]
@kayladnls thnx, added PR #4

**Comment by zaporylie** [comment]
This issue can be closed, right?
