### ISSUE TITLE
TLS 1.0 will be disabled

### ISSUE THREAD

**Issue by hpeide** [thephpleague/omnipay-netaxept#8]
Nettaxpt announced that they will disable TLS 1.0 at November 1. Will that be an issue for existing implementations?

http://www.anpdm.com/newsletterweb/444A5842794842504376444359/424A58417043425B4B764142514171

**Comment by delatbabel** [comment]
The issue relates to the setup of servers running the gateway.  For example, the later versions of OpenSSL and libcurl must be installed. Old servers such as CentOS 5, Debian 5 and earlier may have issues. This isn't really related to the omnipay code or the netaxept gateway.

Most gateway providers have already switched over to supporting TLS 1.2 only.
